### ISSUE TITLE
Make explanatory text less misleading/scary

### ISSUE THREAD

**Issue by jwheare** [mxcl/playdar.prefpane#5]
Playdar won't "search further afield" by default. People will inevitably ask what this means. I'm happy to have a stab at rewriting this. Will post a comment here later.

**Comment by mxcl** [comment]
Well it probably will in the near future depending on the router concept.

I felt it was important to try and push a marketing message. These things get a lot of screenshots, etc.

But agreed, I'm not especially happy with it, nothing better came to mind though.

**Comment by mxcl** [comment]
Yeah, the more I read it the more I agree it needs improvement.

**Comment by mxcl** [comment]
I consider this a showstopper for the Sparkle update.

**Comment by jwheare** [comment]
Just change the last sentence to this:

"Playdar searches this computer, your local network, and can be configured to search other music sources until it finds that track."

**Comment by mxcl** [comment]
Yeah this may do. I prefer the certainty as it stands currently.

**Comment by jwheare** [comment]
Yeah needs more work for sure. This shouldn't be blocking updates for now though.

**Comment by mxcl** [comment]
It's only blocking the sparkle update, as then we throw this new one at all the people from before. All 10 of them or whatever. But I also will stamp it "ready for everyone" at that point so I'd want it to be in a state where we are happy with it.

**Comment by mxcl** [comment]
So yeah to be clear, all the builds last week weren't sparkled.

I only have a couple more fixes to apply and it's ready, just want the copy to be polished too.

**Comment by mxcl** [comment]
Fixed in latest update, though not yet pushed. Though, opinions welcome.
