### ISSUE TITLE
Changing music directory should trigger a rescan.

### ISSUE THREAD

**Issue by jwheare** [mxcl/playdar.prefpane#7]
This may already happen but I see no visual feedback, even when toggling off and on again.

**Comment by mxcl** [comment]
There is some trouble with the latter, as playdar doesn't remember what directories have been scanned. However it needs to, so when that is implemented I can make the latter work.

Making it scan when you select is easy though.

**Comment by mxcl** [comment]
Scan when a new directory item is selected

Closed by 8743bcfaa6c31d156c581700ea4d68657c71e4c0
