### ISSUE TITLE
Ability to add multiple scan directories

### ISSUE THREAD

**Issue by jwheare** [mxcl/playdar.prefpane#8]
I have music in ~/Music as well as ~/Downloads and ~/Desktop sometimes.

**Comment by mxcl** [comment]
Yeah, I'm not interested in supporting this in the GUI. I consider this advanced usage. Most people have a single directory. You can add more directories with playdarctl. Decent argument will sway me however, as always.

**Comment by jwheare** [comment]
Good good. Missing features are allowed :)

**Comment by jwheare** [comment]
Oh I tried to close this but couldn't. Feel free.
